services:
  - type: web
    name: cefr-feedback
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app_v1.py
    # No HF_TOKEN needed, we are loading the model locally

